language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - cp .env.example .env
  - composer update --prefer-source
  - composer install --no-interaction
  - php artisan key:generate
 

script: vendor/bin/phpunit